application:
  version: 0.0.5
  label: test
  name: spring-cloud-config
  details:
    user: config-test
    server:
      addr: http://localhost:8040/
      port: 8040
    client:
      addr: http://localhost:8041/
      port: 8041
message:
  hello: Hello! I'm in config-test branch dev version 0.0.5.
